"""
Hotel Magnifique — Player Preferences (language, currency, difficulty)

Central metadata for the "Opciones" menu plus server-side translations
for the full in-game UI (menu, options, tutorial, ranking, play, results,
and end screen). Translations are consumed through the global ``tr``
context processor; the preference is persisted per player.
"""
from __future__ import annotations

# ── Allowed values (kept in sync with app/models/configuracion.py) ──────
LANGUAGES: tuple[tuple[str, str], ...] = (
    ("es", "Español"),
    ("en", "English"),
    ("fr", "Français"),
    ("de", "Deutsch"),
    ("it", "Italiano"),
)

CURRENCIES: tuple[tuple[str, str], ...] = (
    ("eur", "Euro (€)"),
    ("usd", "US Dollar ($)"),
    ("ars", "Peso argentino (ARS$)"),
)

DIFFICULTIES: tuple[tuple[str, str], ...] = (
    ("facil", "Fácil"),
    ("media", "Media"),
    ("dificil", "Difícil"),
)

# Defaults applied when a player has no saved configuration yet.
DEFAULT_LANGUAGE = "es"
DEFAULT_CURRENCY = "usd"
DEFAULT_DIFFICULTY = "media"

CURRENCY_SYMBOLS: dict[str, str] = {
    "eur": "€",
    "usd": "$",
    "ars": "ARS$",
}

# ECMAScript locales used to format numbers client-side (toLocaleString).
LOCALES: dict[str, str] = {
    "es": "es-ES",
    "en": "en-US",
    "fr": "fr-FR",
    "de": "de-DE",
    "it": "it-IT",
}

LANGUAGE_CODES = {code for code, _ in LANGUAGES}
CURRENCY_CODES = {code for code, _ in CURRENCIES}
DIFFICULTY_CODES = {code for code, _ in DIFFICULTIES}


def money(amount, currency: str = DEFAULT_CURRENCY) -> str:
    """Formats an amount with the configured currency symbol."""
    symbol = CURRENCY_SYMBOLS.get(currency, CURRENCY_SYMBOLS[DEFAULT_CURRENCY])
    try:
        value = float(amount)
    except (TypeError, ValueError):
        value = 0.0
    return f"{symbol}{value:,.0f}"


# ── Translations (menu family screens) ─────────────────────────────────
TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "tagline": "El Arte de la Hospitalidad",
        "welcome": "Bienvenido, {name}",
        "new_game": "Comenzar juego",
        "continue_game": "Continuar partida",
        "tutorial": "Tutorial",
        "options": "Opciones",
        "ranking": "Ranking de jugadores",
        "exit": "Salir",
        "new_game_hint": "Iniciá una nueva temporada de 30 días.",
        "continue_game_hint": "Retomá tu partida en curso.",
        "tutorial_hint": "Aprendé a jugar con el manual del jugador.",
        "options_hint": "Idioma, moneda y dificultad.",
        "ranking_hint": "Los mejores jugadores del servidor.",
        "exit_hint": "Cerrar la sesión y salir del juego.",
        "active_game": "Partida en curso · Día {day} de 30",
        "no_active_game": "Sin partida en curso",
        "continue_disabled": "No tenés una partida pendiente por terminar.",
        "confirm_new": "Ya tenés una partida activa (Día {day}). ¿Empezar una nueva y archivar la actual?",
        "new_ok": "¡Nueva partida iniciada! Día 1 de 30.",
        "options_title": "Opciones",
        "language": "Idioma",
        "currency": "Moneda",
        "difficulty": "Dificultad",
        "difficulty_easy": "Fácil — la demanda de los servicios del hotel es alta casi todos los días.",
        "difficulty_medium": "Media — dificultad por defecto.",
        "difficulty_hard": "Difícil — los cambios de demanda son abruptos.",
        "save": "Guardar cambios",
        "back": "← Volver al menú",
        "saved": "Opciones guardadas.",
        "ranking_title": "Ranking de Jugadores",
        "col_player": "Jugador",
        "col_gain": "Ganancia",
        "col_rep": "Reputación",
        "col_grade": "Grado",
        "col_days": "Días",
        "ranking_empty": "Todavía no hay partidas terminadas.",
        "tutorial_title": "Tutorial",
        "nav_day": "Día",
        "nav_capital": "Capital",
        "nav_rep": "Reputación",
        "logout": "Cerrar sesión",
        "menu_back": "← Volver al menú",
        "forecast_title": "◆ Pronóstico del Día",
        "season": "Temporada",
        "event": "Evento",
        "demand": "Demanda",
        "event_quiet": "Un día tranquilo.",
        "demand_medium": "MEDIA",
        "decisions_title": "◆ Tus Decisiones de Hoy",
        "price_night": "🏷️ Precio/noche",
        "price_hint_moderate": "Precio moderado.",
        "staff_line": "👨‍💼 Personal ({price}/persona)",
        "persons": "personas",
        "marketing_label": "📢 Marketing",
        "services_label": "🛎️ Servicios",
        "breakfast": "Desayuno",
        "pool": "Piscina",
        "spa": "Spa",
        "estimate_title": "◆ Estimación del día",
        "rooms": "Habitaciones",
        "revenue": "Ingresos",
        "expenses": "Gastos",
        "balance": "Balance",
        "hotel_state": "◆ Estado del Hotel",
        "occupancy_yesterday": "Ocupación ayer",
        "profit_yesterday": "Ganancia ayer",
        "reputation": "Reputación",
        "open_hotel": "🏨 Abrir el Hotel — Día {day}",
        "report_title": "Informe del Día {day}",
        "ops_summary": "Resumen de operaciones",
        "occupancy": "Ocupación",
        "day_balance": "Balance del día",
        "next_day": "Día Siguiente →",
        "view_final": "🏆 Ver Resultados Finales",
        "season_complete": "¡Temporada Completada!",
        "final_capital": "Capital final",
        "total_profit": "Ganancia total",
        "final_reputation": "Reputación final",
        "days_played": "Días jugados",
        "play_again": "✦ Jugar de Nuevo ✦",
        "invalid_options": "Valores de opciones inválidos.",
    },
    "en": {
        "tagline": "The Art of Hospitality",
        "welcome": "Welcome, {name}",
        "new_game": "Start Game",
        "continue_game": "Continue Game",
        "tutorial": "Tutorial",
        "options": "Options",
        "ranking": "Player Rankings",
        "exit": "Exit",
        "new_game_hint": "Start a fresh 30-day season.",
        "continue_game_hint": "Resume your game in progress.",
        "tutorial_hint": "Learn how to play with the player manual.",
        "options_hint": "Language, currency and difficulty.",
        "ranking_hint": "The best players on the server.",
        "exit_hint": "Log out and leave the game.",
        "active_game": "Game in progress · Day {day} of 30",
        "no_active_game": "No game in progress",
        "continue_disabled": "You don't have an unfinished game to resume.",
        "confirm_new": "You already have an active game (Day {day}). Start a new one and archive the current one?",
        "new_ok": "New game started! Day 1 of 30.",
        "options_title": "Options",
        "language": "Language",
        "currency": "Currency",
        "difficulty": "Difficulty",
        "difficulty_easy": "Easy — demand for hotel services is high almost every day.",
        "difficulty_medium": "Medium — default difficulty.",
        "difficulty_hard": "Hard — demand changes are abrupt.",
        "save": "Save changes",
        "back": "← Back to menu",
        "saved": "Options saved.",
        "ranking_title": "Player Rankings",
        "col_player": "Player",
        "col_gain": "Profit",
        "col_rep": "Reputation",
        "col_grade": "Grade",
        "col_days": "Days",
        "ranking_empty": "No finished games yet.",
        "tutorial_title": "Tutorial",
        "nav_day": "Day",
        "nav_capital": "Capital",
        "nav_rep": "Reputation",
        "logout": "Log out",
        "menu_back": "← Back to menu",
        "forecast_title": "◆ Daily Forecast",
        "season": "Season",
        "event": "Event",
        "demand": "Demand",
        "event_quiet": "A calm day.",
        "demand_medium": "MEDIUM",
        "decisions_title": "◆ Your Decisions Today",
        "price_night": "🏷️ Price/night",
        "price_hint_moderate": "Moderate price.",
        "staff_line": "👨‍💼 Staff ({price}/person)",
        "persons": "staff",
        "marketing_label": "📢 Marketing",
        "services_label": "🛎️ Services",
        "breakfast": "Breakfast",
        "pool": "Pool",
        "spa": "Spa",
        "estimate_title": "◆ Day Estimate",
        "rooms": "Rooms",
        "revenue": "Revenue",
        "expenses": "Expenses",
        "balance": "Balance",
        "hotel_state": "◆ Hotel Status",
        "occupancy_yesterday": "Yesterday's occupancy",
        "profit_yesterday": "Yesterday's profit",
        "reputation": "Reputation",
        "open_hotel": "🏨 Open the Hotel — Day {day}",
        "report_title": "Day {day} Report",
        "ops_summary": "Operations summary",
        "occupancy": "Occupancy",
        "day_balance": "Day balance",
        "next_day": "Next Day →",
        "view_final": "🏆 View Final Results",
        "season_complete": "Season Complete!",
        "final_capital": "Final capital",
        "total_profit": "Total profit",
        "final_reputation": "Final reputation",
        "days_played": "Days played",
        "play_again": "✦ Play Again ✦",
        "invalid_options": "Invalid option values.",
    },
    "fr": {
        "tagline": "L'Art de l'Hospitalité",
        "welcome": "Bienvenue, {name}",
        "new_game": "Commencer le jeu",
        "continue_game": "Continuer la partie",
        "tutorial": "Tutoriel",
        "options": "Options",
        "ranking": "Classement des joueurs",
        "exit": "Quitter",
        "new_game_hint": "Commencer une nouvelle saison de 30 jours.",
        "continue_game_hint": "Reprendre votre partie en cours.",
        "tutorial_hint": "Apprenez à jouer avec le manuel du joueur.",
        "options_hint": "Langue, devise et difficulté.",
        "ranking_hint": "Les meilleurs joueurs du serveur.",
        "exit_hint": "Se déconnecter et quitter le jeu.",
        "active_game": "Partie en cours · Jour {day} sur 30",
        "no_active_game": "Aucune partie en cours",
        "continue_disabled": "Vous n'avez aucune partie inachevée à reprendre.",
        "confirm_new": "Vous avez déjà une partie active (Jour {day}). En commencer une nouvelle et archiver l'actuelle ?",
        "new_ok": "Nouvelle partie lancée ! Jour 1 sur 30.",
        "options_title": "Options",
        "language": "Langue",
        "currency": "Devise",
        "difficulty": "Difficulté",
        "difficulty_easy": "Facile — la demande des services de l'hôtel est élevée presque chaque jour.",
        "difficulty_medium": "Moyenne — difficulté par défaut.",
        "difficulty_hard": "Difficile — les changements de demande sont brusques.",
        "save": "Enregistrer les modifications",
        "back": "← Retour au menu",
        "saved": "Options enregistrées.",
        "ranking_title": "Classement des Joueurs",
        "col_player": "Joueur",
        "col_gain": "Bénéfice",
        "col_rep": "Réputation",
        "col_grade": "Note",
        "col_days": "Jours",
        "ranking_empty": "Aucune partie terminée pour le moment.",
        "tutorial_title": "Tutoriel",
        "nav_day": "Jour",
        "nav_capital": "Capital",
        "nav_rep": "Réputation",
        "logout": "Se déconnecter",
        "menu_back": "← Retour au menu",
        "forecast_title": "◆ Prévisions du Jour",
        "season": "Saison",
        "event": "Événement",
        "demand": "Demande",
        "event_quiet": "Une journée calme.",
        "demand_medium": "MOYENNE",
        "decisions_title": "◆ Vos Décisions du Jour",
        "price_night": "🏷️ Prix/nuit",
        "price_hint_moderate": "Prix modéré.",
        "staff_line": "👨‍💼 Personnel ({price}/personne)",
        "persons": "personnes",
        "marketing_label": "📢 Marketing",
        "services_label": "🛎️ Services",
        "breakfast": "Petit-déjeuner",
        "pool": "Piscine",
        "spa": "Spa",
        "estimate_title": "◆ Estimation du Jour",
        "rooms": "Chambres",
        "revenue": "Revenus",
        "expenses": "Dépenses",
        "balance": "Bilan",
        "hotel_state": "◆ État de l'Hôtel",
        "occupancy_yesterday": "Occupation hier",
        "profit_yesterday": "Bénéfice hier",
        "reputation": "Réputation",
        "open_hotel": "🏨 Ouvrir l'Hôtel — Jour {day}",
        "report_title": "Rapport du Jour {day}",
        "ops_summary": "Résumé des opérations",
        "occupancy": "Occupation",
        "day_balance": "Bilan du jour",
        "next_day": "Jour Suivant →",
        "view_final": "🏆 Voir les Résultats Finaux",
        "season_complete": "Saison Terminée !",
        "final_capital": "Capital final",
        "total_profit": "Bénéfice total",
        "final_reputation": "Réputation finale",
        "days_played": "Jours joués",
        "play_again": "✦ Rejouer ✦",
        "invalid_options": "Valeurs d'options invalides.",
    },
    "de": {
        "tagline": "Die Kunst der Gastfreundschaft",
        "welcome": "Willkommen, {name}",
        "new_game": "Spiel starten",
        "continue_game": "Spiel fortsetzen",
        "tutorial": "Tutorial",
        "options": "Optionen",
        "ranking": "Spieler-Rangliste",
        "exit": "Beenden",
        "new_game_hint": "Eine neue 30-Tage-Saison beginnen.",
        "continue_game_hint": "Dein laufendes Spiel fortsetzen.",
        "tutorial_hint": "Lerne das Spiel mit dem Spieler-Handbuch.",
        "options_hint": "Sprache, Währung und Schwierigkeit.",
        "ranking_hint": "Die besten Spieler des Servers.",
        "exit_hint": "Abmelden und das Spiel verlassen.",
        "active_game": "Laufendes Spiel · Tag {day} von 30",
        "no_active_game": "Kein laufendes Spiel",
        "continue_disabled": "Du hast kein unvollendetes Spiel zum Fortsetzen.",
        "confirm_new": "Du hast bereits ein aktives Spiel (Tag {day}). Ein neues starten und das aktuelle archivieren?",
        "new_ok": "Neues Spiel gestartet! Tag 1 von 30.",
        "options_title": "Optionen",
        "language": "Sprache",
        "currency": "Währung",
        "difficulty": "Schwierigkeit",
        "difficulty_easy": "Einfach — die Nachfrage nach Hotelservices ist fast jeden Tag hoch.",
        "difficulty_medium": "Mittel — Standard-Schwierigkeit.",
        "difficulty_hard": "Schwer — Nachfrageänderungen sind abrupt.",
        "save": "Änderungen speichern",
        "back": "← Zurück zum Menü",
        "saved": "Optionen gespeichert.",
        "ranking_title": "Spieler-Rangliste",
        "col_player": "Spieler",
        "col_gain": "Gewinn",
        "col_rep": "Ruf",
        "col_grade": "Note",
        "col_days": "Tage",
        "ranking_empty": "Noch keine beendeten Spiele.",
        "tutorial_title": "Tutorial",
        "nav_day": "Tag",
        "nav_capital": "Kapital",
        "nav_rep": "Ruf",
        "logout": "Abmelden",
        "menu_back": "← Zurück zum Menü",
        "forecast_title": "◆ Tagesprognose",
        "season": "Saison",
        "event": "Ereignis",
        "demand": "Nachfrage",
        "event_quiet": "Ein ruhiger Tag.",
        "demand_medium": "MITTEL",
        "decisions_title": "◆ Deine Entscheidungen Heute",
        "price_night": "🏷️ Preis/Nacht",
        "price_hint_moderate": "Moderater Preis.",
        "staff_line": "👨‍💼 Personal ({price}/Person)",
        "persons": "Personen",
        "marketing_label": "📢 Marketing",
        "services_label": "🛎️ Dienstleistungen",
        "breakfast": "Frühstück",
        "pool": "Pool",
        "spa": "Spa",
        "estimate_title": "◆ Tagesschätzung",
        "rooms": "Zimmer",
        "revenue": "Einnahmen",
        "expenses": "Ausgaben",
        "balance": "Bilanz",
        "hotel_state": "◆ Hotelstatus",
        "occupancy_yesterday": "Belegung gestern",
        "profit_yesterday": "Gewinn gestern",
        "reputation": "Ruf",
        "open_hotel": "🏨 Hotel öffnen — Tag {day}",
        "report_title": "Tagesbericht Tag {day}",
        "ops_summary": "Betriebsübersicht",
        "occupancy": "Belegung",
        "day_balance": "Tagesbilanz",
        "next_day": "Nächster Tag →",
        "view_final": "🏆 Endresultate anzeigen",
        "season_complete": "Saison Abgeschlossen!",
        "final_capital": "Endkapital",
        "total_profit": "Gesamtgewinn",
        "final_reputation": "Endruf",
        "days_played": "Gespielte Tage",
        "play_again": "✦ Erneut Spielen ✦",
        "invalid_options": "Ungültige Optionswerte.",
    },
    "it": {
        "tagline": "L'Arte dell'Ospitalità",
        "welcome": "Benvenuto, {name}",
        "new_game": "Inizia gioco",
        "continue_game": "Continua partita",
        "tutorial": "Tutorial",
        "options": "Opzioni",
        "ranking": "Classifica giocatori",
        "exit": "Esci",
        "new_game_hint": "Inizia una nuova stagione di 30 giorni.",
        "continue_game_hint": "Riprendi la tua partita in corso.",
        "tutorial_hint": "Impara a giocare con il manuale del giocatore.",
        "options_hint": "Lingua, valuta e difficoltà.",
        "ranking_hint": "I migliori giocatori del server.",
        "exit_hint": "Esci dalla sessione e dal gioco.",
        "active_game": "Partita in corso · Giorno {day} di 30",
        "no_active_game": "Nessuna partita in corso",
        "continue_disabled": "Non hai partite incomplete da riprendere.",
        "confirm_new": "Hai già una partita attiva (Giorno {day}). Iniziarne una nuova e archiviare quella attuale?",
        "new_ok": "Nuova partita iniziata! Giorno 1 di 30.",
        "options_title": "Opzioni",
        "language": "Lingua",
        "currency": "Valuta",
        "difficulty": "Difficoltà",
        "difficulty_easy": "Facile — la domanda dei servizi dell'hotel è alta quasi ogni giorno.",
        "difficulty_medium": "Media — difficoltà predefinita.",
        "difficulty_hard": "Difficile — i cambiamenti della domanda sono bruschi.",
        "save": "Salva modifiche",
        "back": "← Torna al menu",
        "saved": "Opzioni salvate.",
        "ranking_title": "Classifica Giocatori",
        "col_player": "Giocatore",
        "col_gain": "Profitto",
        "col_rep": "Reputazione",
        "col_grade": "Voto",
        "col_days": "Giorni",
        "ranking_empty": "Nessuna partita terminata.",
        "tutorial_title": "Tutorial",
        "nav_day": "Giorno",
        "nav_capital": "Capitale",
        "nav_rep": "Reputazione",
        "logout": "Esci",
        "menu_back": "← Torna al menu",
        "forecast_title": "◆ Previsioni del Giorno",
        "season": "Stagione",
        "event": "Evento",
        "demand": "Domanda",
        "event_quiet": "Una giornata tranquilla.",
        "demand_medium": "MEDIA",
        "decisions_title": "◆ Le Tue Decisioni di Oggi",
        "price_night": "🏷️ Prezzo/notte",
        "price_hint_moderate": "Prezzo moderato.",
        "staff_line": "👨‍💼 Personale ({price}/persona)",
        "persons": "persone",
        "marketing_label": "📢 Marketing",
        "services_label": "🛎️ Servizi",
        "breakfast": "Colazione",
        "pool": "Piscina",
        "spa": "Spa",
        "estimate_title": "◆ Stima del Giorno",
        "rooms": "Camere",
        "revenue": "Entrate",
        "expenses": "Spese",
        "balance": "Bilancio",
        "hotel_state": "◆ Stato dell'Hotel",
        "occupancy_yesterday": "Occupazione ieri",
        "profit_yesterday": "Guadagno ieri",
        "reputation": "Reputazione",
        "open_hotel": "🏨 Apri l'Hotel — Giorno {day}",
        "report_title": "Report del Giorno {day}",
        "ops_summary": "Riepilogo delle operazioni",
        "occupancy": "Occupazione",
        "day_balance": "Bilancio del giorno",
        "next_day": "Giorno Successivo →",
        "view_final": "🏆 Vedi Risultati Finali",
        "season_complete": "Stagione Completata!",
        "final_capital": "Capitale finale",
        "total_profit": "Profitto totale",
        "final_reputation": "Reputazione finale",
        "days_played": "Giorni giocati",
        "play_again": "✦ Gioca di Nuovo ✦",
        "invalid_options": "Valori opzioni non validi.",
    },
}


def translate(language: str) -> dict[str, str]:
    """Returns the translation table for a language (Spanish fallback)."""
    table = TRANSLATIONS.get(language)
    if table is None:
        table = TRANSLATIONS[DEFAULT_LANGUAGE]
    merged = dict(TRANSLATIONS[DEFAULT_LANGUAGE])
    merged.update(table)
    return merged