"""init

Revision ID: 6efc9f58613a
Revises: 
Create Date: 2026-04-25 15:51:43.998407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efc9f58613a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('partida',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('dia_actual', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reputacion', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('ganancia_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ingreso_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gasto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('grado_final', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partida_usuario_id'), 'partida', ['usuario_id'], unique=False)
    op.create_table('ajuste',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partida_id', sa.String(length=36), nullable=False),
    sa.Column('parametro', sa.String(length=50), nullable=False),
    sa.Column('valor_base', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_actual', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ajuste_partida_id'), 'ajuste', ['partida_id'], unique=False)
    op.create_table('dia',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partida_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('factor_temporada', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('factor_evento', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dia_partida_id'), 'dia', ['partida_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dia_id', sa.String(length=36), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('personal', sa.Integer(), nullable=False),
    sa.Column('marketing', sa.Integer(), nullable=False),
    sa.Column('desayuno', sa.Boolean(), nullable=False),
    sa.Column('piscina', sa.Boolean(), nullable=False),
    sa.Column('spa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dia_id'], ['dia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_dia_id'), 'decision', ['dia_id'], unique=False)
    op.create_table('resultado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dia_id', sa.String(length=36), nullable=False),
    sa.Column('habitaciones_ocupadas', sa.Integer(), nullable=False),
    sa.Column('ocupacion_pct', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('ingreso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gasto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reputacion', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('reputacion_cambio', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('demanda_base', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('precio_optimo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dia_id'], ['dia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_dia_id'), 'resultado', ['dia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_dia_id'), table_name='resultado')
    op.drop_table('resultado')
    op.drop_index(op.f('ix_decision_dia_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_dia_partida_id'), table_name='dia')
    op.drop_table('dia')
    op.drop_index(op.f('ix_ajuste_partida_id'), table_name='ajuste')
    op.drop_table('ajuste')
    op.drop_index(op.f('ix_partida_usuario_id'), table_name='partida')
    op.drop_table('partida')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
